### ISSUE TITLE
Full hierarchy is not getting added in Address table

### ISSUE THREAD

**Issue by sachsk** [avniproject/avni-etl#31] opened 2023-03-13 10:14 UTC
In RWB district taluka missing for  some dams.

#### Locations in DB
`
set role rwbka; 
select dam.title,dam.type_id,tal.title,tal.type_id,dist.title,dist.type_id
from address_level dam
left join address_level tal on tal.id=dam.parent_id
left join address_level dist on dist.id=tal.parent_id
where dam.id in (
                 373674,
                 373675,
                 116208,
                 373676
    )`
#### Location in ETL Table

`select *
from organisation;
select *
from rwb.address where id in (
    373674,
373675,
116208,
373676
    );`

Reference ticket:
https://avni.freshdesk.com/a/tickets/2380

**Comment by vinayvenu** [comment] 2023-03-14 08:47
This is caused by bad data. The dams in question have an incorrect location hierarchy.

**Comment by vinayvenu** [comment] 2023-03-17 05:00
Issue fixed. Closing this issue.

**Closed by vinayvenu** 2023-03-17 05:00 UTC
Labels: bug, FreshDesk
